module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    // Important: Do not heavily cache the router response itself, so we can route dynamically
    res.setHeader('Cache-Control', 's-maxage=1, stale-while-revalidate=5');

    const { id } = req.query;

    if (!id) {
        return res.status(400).send("Missing 'id' parameter.");
    }

    // V8 Titan Anti-Piracy Token Security
    const expectedToken = process.env.AUTH_TOKEN;
    if (expectedToken) {
        const { token } = req.query;
        if (!token || token !== expectedToken) {
            return res.status(403).send("Forbidden: Invalid or missing authorization token.");
        }
    }

    // Determine the base URL to fetch the router.json
    const protocol = req.headers['x-forwarded-proto'] || 'https';
    const baseUrl = `${protocol}://${req.headers.host}`;
    
    try {
        // Fetch the routing table generated by the Python engine
        const routerUrl = `${baseUrl}/output/router.json`;
        const routerRes = await fetch(routerUrl);
        
        if (!routerRes.ok) {
            throw new Error(`Failed to load routing table: ${routerRes.status}`);
        }
        
        const routerData = await routerRes.json();
        const sources = routerData[id];

        if (!sources || !Array.isArray(sources) || sources.length === 0) {
            return res.status(404).send("Channel not found or no sources available.");
        }

        // Auto-Healing Logic: Check streams sequentially to find the first alive one
        for (const source of sources) {
            try {
                // Do a lightweight HEAD or fast GET request to check if the stream is alive
                const checkRes = await fetch(source, {
                    method: 'GET',
                    headers: { 'Range': 'bytes=0-1024' }, // Only fetch a tiny byte range to save bandwidth
                    signal: AbortSignal.timeout(2000) // 2 second timeout per source
                });

                // If the stream returns a 2xx or 3xx (or 206 Partial Content), it's alive!
                if (checkRes.ok || checkRes.status === 206 || checkRes.status === 302) {
                    // Redirect the user's video player to the healthy stream
                    res.writeHead(302, { Location: source });
                    return res.end();
                }
            } catch (e) {
                // Source timed out or failed, silently move to the next backup source
                console.warn(`Source failed for ${id}: ${source} - ${e.message}`);
                continue;
            }
        }

        // If all sources are dead, return an error (or a custom offline video)
        return res.status(502).send("All upstream sources for this channel are currently offline.");

    } catch (error) {
        console.error("Router Error:", error);
        return res.status(500).send(`Internal Server Error: ${error.message}`);
    }
};
